apps/adopcion/urls.py
from django.contrib import admin
from django.urls import path,include
from apps.adopcion import views

urlpatterns = [
	path("",views.index_adopcion, name="index_adopcion")
]

apps/mascota/urls.py
from django.contrib import admin
from django.urls import path,include
# from . import views
from apps.mascota import views

app_name ='mascota'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'nuevo', views.mascota_view, name="mascota_new"),
    path(r'crear', views.mascota_crear, name="mascota_crear"),
    path(r'listar', views.mascota_listar, name="mascota_listar"),
    path(r'editar/<int:id_mascota>/', views.mascota_editar, name="mascota_editar"),
    path(r'eliminar/<int:id_mascota>/', views.mascota_eliminar, name="mascota_eliminar"),
]

codigofacilito1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include('apps.mascota.urls')),
    path('adopcion/', include('apps.adopcion.urls')),
]

apps/adopcion/models.py
from django.db import models

class Persona(models.Model):
	nombre = models.CharField(max_length=50)
	apellido = models.CharField(max_length=50)
	edad = models.IntegerField()
	telefono =  models.CharField(max_length=12)
	email = models.EmailField()
	domicilio = models.TextField()

	def __str__(self):
		return self.nombre

apps/mascota/models.py
from django.db import models
from apps.adopcion.models import Persona

"""
relacion uno a muchos 
una persona puede tener muchas mascotas

relacion muchos a muchos
una vacuna se puede aplicar a muchas mascotas 
y una mascota puede tener muchas vacunas 
"""

class Vacuna(models.Model):
	nombre = models.CharField(max_length=50)
	def __str__(self):
		return self.nombre

class Mascota(models.Model):
	nombre = models.CharField(max_length=50)
	sexo = models.CharField(max_length=10)
	edad_aproximada = models.IntegerField()
	fecha_rescate = models.DateField()
	persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
	vacuna = models.ManyToManyField(Vacuna,blank=True)
	def __str__(self):
		return self.nombre


	








# Persona.objects.create(nombre="ramon ",apellido="calzadilla",edad=23,telefono="123654",email="william@gmail.com",domicilio="afafaf")


# # uno a muchos 
# m=Mascota(nombre="simon perrito",sexo="macho",edad_aproximada=2,fecha_rescate="2020-07-16",persona=p)
# m.save()

# # muchos a muchos

# >>> v1=Vacuna.objects.get(id=1)
# >>> v2=Vacuna.objects.get(id=2)
# >>> v1
# p=Persona.objects.get(id=1)
# m=Mascota(nombre="simon perrito",sexo="macho",edad_aproximada=2,fecha_rescate="2020-07-16",persona=p)
# >>> v1=Vacuna.objects.get(id=1)
# >>> v2=Vacuna.objects.get(id=2)
# # muchos a muchos
# m.vacuna.add(v1,v2)

# y aqui no es necesario hacer .save()

apps/mascota/forms.py
from django import forms

from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):

	class Meta:
		model = Mascota
		fields = [
			'nombre',
			'sexo',
			'edad_aproximada',
			'fecha_rescate',
			'persona',
			'vacuna',
		]

		labels ={
			'nombre':'nombre',
			'sexo':'sexo',
			'edad_aproximada':'edad_aproximada',
			'fecha_rescate':'fecha_rescate',
			'persona':'persona',
			'vacuna':'vacuna',
		} 
		widgets ={
			'nombre':forms.TextInput(attrs={'class':'form-control'}),
			'sexo':forms.TextInput(attrs={'class':'form-control'}),
			'edad_aproximada':forms.TextInput(attrs={'class':'form-control'}),
			'fecha_rescate':forms.TextInput(attrs={'class':'form-control'}),
			'persona':forms.Select(attrs={'class':'form-control'}),
			'vacuna':forms.CheckboxSelectMultiple(),
		} 

apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index_adopcion(request):
	# return HttpResponse("Este es el index de adopcion")
	return render(request, 'adopcion/index.html')

apps/mascota/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
# from . import forms
from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota
import pdb

def index(request):
	# return HttpResponse("este es el index de mascota") 
	return render(request,'mascota/index.html') 

def mascota_view(request):
	form = MascotaForm()
	return render(request,'mascota/mascota_form.html',{'form':form})

def mascota_crear(request):
	if request.method == 'POST':
		form = MascotaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('mascota:index')
	else:
		form = MascotaForm()
	return render(request,'mascota/mascota_form.html',{'form':form})

def mascota_listar(request):
	all_mascota = Mascota.objects.all().order_by('id')
	context = {
		'mascotas':all_mascota

	}
	return render(request, 'mascota/mascota_list.html', context)

def mascota_editar(request,id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'GET':
		form = MascotaForm(instance=mascota)
	else:
		form = MascotaForm(request.POST, instance= mascota)
		if form.is_valid():
			form.save()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_form.html',{'form':form})

def mascota_eliminar(request,id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':
		mascota.delete()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_eliminar.html',{'mascota':mascota})

templates/adopcion/index.html
<h1>este es el index de aopcion</h1>

templates/base/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	{% block extrahead %}
	{% endblock %}
	<!-- el tag static lo que hace es generar la ruta absoluta de mi archivo -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
	<title>{% block title %}Document {% endblock %}</title>
</head>
<body>
	<div class="container">
	{% block header %}
	<h4>Este es el bloque del header base</h4>	
	{% endblock %}	

	{% block content %}
	
	{% endblock %}

	{% block footer %}
	<h5>Soy el footer del base</h5>
	{% endblock %}

	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	{% block extrajs %}
	{% endblock  %}
	</div>
</body>
</html>

templates/base/header.html
<header>william heade</header>

templates/mascota/index.html
{% extends "base/base.html" %}

{%block header%}
<h4>este el bloque del header index mascota </h4>
<!-- {%include 'base/header.html'%} -->
{% endblock %}

{% block content %}
<h1>este es el index de mascotas</h1>


<h5>es es el contenido del archio base</h5>
<a class="btn btn-primary" href="{% url 'mascota:mascota_listar'%}">ir a listar </a>
	
{% endblock %}

templates/mascota/mascota_eliminar.html
{% extends 'base/base.html' %}
{% block content %}

<h1>my formulario de mascotas</h1>
<form  method="POST" >
	{% csrf_token %}
	<h3>¿desea eliminar el registro de {{mascota.nombre}}?</h3>
	<button type="submit">si, eliminar</button>
</form>
	<a class="btn btn-default" href="{% url 'mascota:mascota_listar '%}">CANCELAR</a>
{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}
{% block content %}

<h1>my formulario de mascotas</h1>
<form action="{% url 'mascota:mascota_crear' %}" method="POST" >
	{% csrf_token %}
	{{form.as_p}}
	<button type="submit">enviar</button>
</form>
{% endblock %}

templates/mascota/mascota_list.html
{%extends 'base/base.html'%}

{% block content%}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Sexo</td>
			<td>Edad</td>
			<td>Fecha de rescate</td>
			<td>Adoptante</td>
			<td>nuevi</td>
			<td>editar</td>
			<td>eliminar</td>
		</tr>
	</thead>
	<tbody>
		{% if mascotas%}
		{% for mascota in mascotas%}
			<tr>
				<td>{{mascota.id}}</td>
				<td>{{mascota.nombre}}</td>
				<td>{{mascota.sexo}}</td>
				<td>{{mascota.edad_aproximada}}</td>
				<td>{{mascota.fecha_rescate}}</td>
				<td>{{mascota.persona}}</td>
				<td> <a class="btn btn-primary" href="{% url 'mascota:mascota_new'  %}">nuevo</a> </td>
				<td> <a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">EDITAR</a> </td>
				<td> <a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">eliminar</a> </td>
			</tr>
		{% endfor %}
		{% else%}
		 	<h1>No hay registros de mascotas en la base de datos </h1>
		{% endif%}
	</tbody>
	
</table>


{% endblock %}